# Generated by Django 4.1 on 2022-10-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.CharField(default=' ', max_length=10, primary_key=True, serialize=False)),
                ('user', models.CharField(default=' ', max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user'))),
                ('product', models.CharField(default=' ', max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product'))),
                ('unit_price', models.CharField(default=' ', max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product'))),
                ('amount', models.CharField(default='1', max_length=5)),
                ('total', models.CharField(default=' ', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=' ', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=' ', max_length=10, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('category', models.CharField(default=' ', max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category'))),
                ('details', models.CharField(default=' ', max_length=10000)),
                ('newprice', models.CharField(default=' ', max_length=10)),
                ('oldprice', models.CharField(blank=True, default=' ', max_length=10)),
                ('count', models.CharField(default=' ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=' ', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('repassword', models.CharField(max_length=100)),
                ('permission', models.CharField(max_length=10)),
            ],
        ),
    ]
