# Generated by Django 4.1.3 on 2022-11-17 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='images/uploads/avatars')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images/uploads/products')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('details', models.CharField(default=' ', max_length=10000)),
                ('newprice', models.CharField(default=' ', max_length=10)),
                ('oldprice', models.CharField(blank=True, default=' ', max_length=10)),
                ('count', models.CharField(default=' ', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GDNusers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDNusers.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.CharField(default=' ', max_length=10, primary_key=True, serialize=False)),
                ('amount', models.CharField(default='1', max_length=5)),
                ('total', models.CharField(default=' ', max_length=15)),
                ('dateofpayment', models.DateField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDNusers.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
