# Generated by Django 4.1.3 on 2022-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDNusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
