# Generated by Django 4.1.3 on 2022-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDNusers', '0002_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
