# Generated by Django 4.1.3 on 2022-11-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDNusers', '0003_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pay',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
