# Generated by Django 4.1.3 on 2022-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDNusers', '0004_alter_cast_id_alter_category_id_alter_pay_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_using', models.BooleanField()),
            ],
        ),
    ]
