# Generated by Django 4.1.3 on 2022-11-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GDNusers', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDNusers.payment')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDNusers.pay')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDNusers.shipper')),
                ('shippingstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDNusers.shipping')),
            ],
        ),
    ]
