# Generated by Django 4.1.3 on 2022-11-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GDNusers', '0006_shipper_shipping_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GDNusers.payment'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GDNusers.pay'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GDNusers.shipper'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shippingstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GDNusers.shipping'),
        ),
    ]
